### ISSUE TITLE
Adding additional permission to the `service_account` that gets attached to the vm.

### ISSUE THREAD

**Issue by jsbroks** [hashicorp/terraform-google-terraform-enterprise#118]
How do I add additional permission to the service account attached to the VM?

**Comment by jsbroks** [comment]
@aaron-lane Im having issues upgrading to the latest version to access `service_account.email`. When will this repo have an offical release and be out of beta?

**Comment by aaron-lane** [comment]
I apologize for the frustrating experience! While I can't provide any estimated date for the next release, I can assure you that this module is going through a significant amount of testing internally to ensure a high degree of quality when that release does occur 📆 Unfortunately, a consequence of that work will be further breaking changes on the `main` branch as we implement a product that we're comfortable supporting.
