### ISSUE TITLE
setup is not running

### ISSUE THREAD

**Issue by serg060606** [hashicorp/terraform-google-terraform-enterprise#127]
The "main" branch has version which is creating infrastructure, but doesn't setup the service.

**Comment by aaron-lane** [comment]
Hi @serg060606! Can you please provide more details about the issue that you are experiencing? The main branch is used in nightly tests of Terraform Enterprise, so it does successfully setup the service in normal circumstances.

**Comment by aaron-lane** [comment]
@serg060606 okay, I think I see the issue. The main branch is under active development, and we have not had an opportunity to update the examples to follow. The examples should be working on the v0.2.0-beta tag, but that is quite out of date at this point. The [tests](https://github.com/hashicorp/terraform-google-terraform-enterprise/tree/main/tests) directory on the main branch has several test configurations which can be reviewed for examples of how the module currently works.

More broadly, please note that until we reach a point where we are comfortable with cutting a new release, the main branch may be subject to further significant changes without warning.

**Comment by serg060606** [comment]
@aaron-lane do you mean that right now repo has no working complete version/branch which could be used for TFE setup ?

**Comment by aaron-lane** [comment]
No, just that the configurations in the `examples` directory are not functioning. The root module and tests on the main branch are fully functional.

**Comment by serg060606** [comment]
in main branch
`│ Error: project: required field is not set
│
│   with module.vm_mig.google_compute_region_instance_group_manager.mig,
│   on .terraform\modules\vm_mig\modules\mig\main.tf line 38, in resource "google_compute_region_instance_group_manager" "mig":
│   38: resource "google_compute_region_instance_group_manager" "mig" {`

**Comment by aaron-lane** [comment]
That message indicates that you have not configured a project for the google provider. You will need to refer to the [google provider documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference) for guidance on how you can accomplish that task.

**Comment by serg060606** [comment]
provider block already mentioned in main file, but it's not fixing the issue, adding to environment variable additional environment variable like "GOOGLE_PROJECT" out of config tf probably is not the best practice and as far I see it works for local modules, but seems is not working for remote.
Next issue in configuration:
'Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.target': 'https://www.googleapis.com/compute/v1/projects/some_project/regions/us-west1/targetHttpsProxies/dev-tfe-internal-lb'. A reserved and active subnetwork is required in the same region and VPC as the forwarding rule., invalid
│
│   with module.private_load_balancer[0].google_compute_forwarding_rule.lb,
│   on modules\private_load_balancer\main.tf line 59, in resource "google_compute_forwarding_rule" "lb":
│   59: resource "google_compute_forwarding_rule" "lb" {'

are you sure that module is working Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.target': 'https://www.googleapis.com/compute/v1/projects/lateral-ceiling-335822/regions/us-west1/targetHttpsProxies/dev-tfe-internal-lb'. A reserved and active subnetwork is required in the same region and VPC as the forwarding rule., invalid
│
│   with module.private_load_balancer[0].google_compute_forwarding_rule.lb,
│   on modules\private_load_balancer\main.tf line 59, in resource "google_compute_forwarding_rule" "lb":
│   59: resource "google_compute_forwarding_rule" "lb" {

**Comment by serg060606** [comment]
Fixed and applied config from "main" branch. its not making service provision as well

**Comment by aaron-lane** [comment]
@serg060606 I can assure you that the main branch _does_ work: we use it in nightly testing of TFE. Can you please share the configuration that you are running?

**Comment by serg060606** [comment]
@aaron-lane I'm sorry, what the config exactly you are asking ? How many nodes ? Provisioning part even not running during the deploy, even not trying to run during booting instances.

**Comment by aaron-lane** [comment]
My apologies for not being clear. Can you please share the Terraform configuration that you are using to invoke this module? 

Our nightly testing includes verification that TFE is deployed and operational by means of a suite of integration tests, not just that the infrastructure is provisioned.

**Comment by serg060606** [comment]
@aaron-lane we found the issue it was "startup-script: /usr/bin/env: ‘bash\r’: No such file or directory."
so "tfe_vm.sh.tpl" has issue with windows kind format of line break.
I'm trying to figure out about reason of "reserve" subnetwork, it is not used in configuration and I would like to remove it. Could you help to find better way to remove "reserve" subnetwork usage, please and will be great to use existent subnetwork without creation any new at all.

**Comment by aaron-lane** [comment]
I'm glad to hear that you identified the source of the startup problem. I assume that means you have forked the configuration as this issue does not exist on the main branch.

The "reserve" subnetwork is a requirement of GCP internal HTTPS load balancing. Conceivably, the design can be updated so that subnetwork is only created when internal load balancing is selected. Would that satisfy your request? As for using an existing subnetwork, you can specify both the `network` and `subnetwork` arguments on the root module, which will disable the use of the networking submodule. Please note this is not a feature that we have actively tested so it may be incomplete.

**Comment by serg060606** [comment]
@aaron-lane unfortunately the issue with windows characters exists in main/root branch here. as well I see different issue right now
/tmp/metadata-scripts852479847/startup-script: line 55: warning: command substitution: ignored null byte in input
which is the issue as well from main branch here. not sure what the tests are going, but assuming tests are not complete covering the repo, at least main branch

**Comment by serg060606** [comment]
@aaron-lane please ignore your tests environment and just try to check the repo on different GCP project. 
startup-script is corrupted, startup-script in "main" official branch is broken. Above several issues at least I found

**Comment by aaron-lane** [comment]
> @aaron-lane unfortunately the issue with windows characters exists in main/root branch here. as well I see different issue right now on the spinning instance: /tmp/metadata-scripts852479847/startup-script: line 55: warning: command substitution: ignored null byte in input which is the issue as well from main branch here. not sure what the tests are going, but assuming tests are not complete covering the repo, at least main branch

Unfortunately, I can not share the nightly build configuration with you as it resides in a private repository, but I can assure you that it uses the main branch of this repository and runs two test scenarios:

- [standalone-external-rhel8-worker](https://github.com/hashicorp/terraform-google-terraform-enterprise/tree/main/tests/standalone-external-rhel8-worker)
- [standalone-mounted-disk](https://github.com/hashicorp/terraform-google-terraform-enterprise/tree/main/tests/standalone-mounted-disk)

These scenarios both successfully deployed and tested TFE as recently as last night. 

I also executed the [3 module test scenarios](https://github.com/hashicorp/terraform-google-terraform-enterprise/pull/128#issuecomment-1006004666) 2 days ago, which also successfully deployed and tested TFE.

> @aaron-lane please ignore your tests environment and just try to check the repo on different GCP project. startup-script is corrupted, startup-script in "main" official branch is broken. Above several issues at least I found

The two sets of tests that I just described run in different GCP projects which are configured independently of each other. Additionally, to my knowledge there is not a GCP project configuration which would cause the startup script to be valid in one and invalid in the other.

@serg060606 if you can please provide a Terraform configuration that we can use to reproduce the issue that you are seeing, or a pull request to this repository that includes [the fix to the issue that you described](https://github.com/hashicorp/terraform-google-terraform-enterprise/issues/127#issuecomment-1006916667) then we can try to assist you further. Otherwise, there is unfortunately not much that we can do at this time as the main branch of this module repository is used in a variety of testing and developing workflows without experiencing the issues that you are describing.

**Comment by serg060606** [comment]
@aaron-lane I can share:
`$ cat -A /terraform-google-terraform-enterprise/modules/user_data/templates/tfe_vm.sh.tpl
#!/usr/bin/env bash^M$
set -e -u -o pipefail^M$
^M$
log_pathname="/var/log/ptfe.log"^M$
echo "[Terraform Enterprise] Setting up" | tee -a $log_pathname^M$
^M$
release_name=$(grep "^NAME=" /etc/os-release | cut -d"\"" -f2)^M$
^M$
echo "[Terraform Enterprise] Detected operating system release name: '$release_name'" | tee -a $log_pathname^M$
^M$
case "$release_name" in^M$
  "Red Hat"*)^M$
    distribution="rhel"^M$
    ;;^M$
  "Ubuntu"*)^M$
    distribution="ubuntu"^M$
    ;;^M$
  *)^M$
    echo "[Terraform Enterprise] Unsupported operating system release in use; exiting" | tee -a $log_pathname^M$
    exit 1^M$
esac^M$
echo "[Terraform Enterprise] Assuming distribution: '$distribution'" | tee -a $log_pathname^M$
^M$
echo "[Terraform Enterprise] Writing Terraform Enterprise settings to '${settings_pathname}'" | tee -a $log_pathname^M$
echo "${settings}" | base64 --decode > ${settings_pathname}^M$
^M$
replicated_conf_pathname="/etc/replicated.conf"^M$
echo "[Terraform Enterprise] Writing Replicated configuration to '$replicated_conf_pathname'" | tee -a $log_pathname^M$
echo "${replicated}" | base64 --decode > $replicated_conf_pathname^M$
^M$
docker_directory="/etc/docker"^M$
echo "[Terraform Enterprise] Creating Docker directory at '$docker_directory'" | tee -a $log_pathname^M$
mkdir -p $docker_directory^M$
docker_daemon_pathname="$docker_directory/daemon.json"^M$
echo "[Terraform Enterprise] Writing Docker daemon to '$docker_daemon_pathname'" | tee -a $log_pathname^M$
echo "${docker_config}" | base64 --decode > $docker_daemon_pathname^M$
^M$
%{ if proxy_ip != null ~}^M$
environment_pathname="/etc/environment"^M$
echo "[Terraform Enterprise] Configuring environment proxy in '$environment_pathname'" | tee -a $log_pathname^M$
/bin/cat <<EOF >>$environment_pathname^M$
http_proxy="http://${proxy_ip}"^M$
https_proxy="https://${proxy_ip}"^M$
no_proxy="${no_proxy}"^M$
EOF^M$
^M$
profile_proxy_pathname="/etc/profile.d/proxy.sh"^M$
echo "[Terraform Enterprise] Configuring profile proxy in '$profile_proxy_pathname'" | tee -a $log_pathname^M$
/bin/cat <<EOF >$profile_proxy_pathname^M$
http_proxy="http://${proxy_ip}"^M$
https_proxy="https://${proxy_ip}"^M$
no_proxy="${no_proxy}"^M$
EOF^M$
^M$
export http_proxy="http://${proxy_ip}"^M$
export https_proxy="https://${proxy_ip}"^M$
export no_proxy="${no_proxy}"^M$
^M$
%{ endif ~}^M$
%{ if ca_certificate_secret != null ~}^M$
ca_certificate_directory="/dev/null"^M$
^M$
if [[ $distribution == "ubuntu" ]]^M$
then^M$
  ca_certificate_directory="/usr/local/share/ca-certificates/extra"^M$
elif [[ $distribution == "rhel" ]]^M$
then^M$
  ca_certificate_directory="/usr/share/pki/ca-trust-source/anchors"^M$
fi^M$
^M$
echo "[Terraform Enterprise] Creating CA certificate directory at '$ca_certificate_directory'" | tee -a $log_pathname^M$
mkdir --parents "$ca_certificate_directory"^M$
^M$
echo "[Terraform Enterprise] Reading CA certificate secret '${ca_certificate_secret}'" | tee -a $log_pathname^M$
certificate_data="$( \^M$
  http_proxy="" https_proxy="" gcloud secrets versions access latest --secret="${ca_certificate_secret}" | \^M$
    base64 --decode --ignore-garbage \^M$
)"^M$
^M$
ca_certificate_pathname="$ca_certificate_directory/tfe-ca-certificate.crt"^M$
echo "[Terraform Enterprise] Writing CA certificate data to '$ca_certificate_pathname'" | tee -a $log_pathname^M$
echo "$certificate_data" > $ca_certificate_pathname^M$
^M$
echo "[Terraform Enterprise] Updating CA certificates" | tee -a $log_pathname^M$
if [[ $distribution == "ubuntu" ]]^M$
then^M$
  update-ca-certificates^M$
elif [[ $distribution == "rhel" ]]^M$
then^M$
  update-ca-trust^M$
fi^M$
^M$
echo "[Terraform Enterprise] Installing jq" | tee -a $log_pathname^M$
if [[ $distribution == "ubuntu" ]]^M$
then^M$
  apt-get --assume-yes update^M$
  apt-get --assume-yes install jq^M$
elif [[ $distribution == "rhel" ]]^M$
then^M$
  yum --assumeyes install jq^M$
fi^M$
^M$
original_settings_pathname="/etc/ptfe-settings-original.json"^M$
echo "[Terraform Enterprise] Copying Terraform Enterprise settings to '$original_settings_pathname'" | tee -a $log_pathname^M$
cp ${settings_pathname} $original_settings_pathname^M$
echo "[Terraform Enterprise] Adding CA certificate data as 'ca_certs' in '${settings_pathname}'" | tee -a $log_pathname^M$
jq ". + { ca_certs: { value: \"$certificate_data\" } }" -- $original_settings_pathname > ${settings_pathname}^M$
^M$
%{ endif ~}^M$
%{ if disk_path != null ~}^M$
device="/dev/${disk_device_name}"^M$
echo "[Terraform Enterprise] Checking disk at '$device' for EXT4 filesystem" | tee -a $log_pathname^M$
^M$
if lsblk --fs $device | grep ext4^M$
then^M$
  echo "[Terraform Enterprise] EXT4 filesystem detected on disk at '$device'" | tee -a $log_pathname^M$
else^M$
  echo "[Terraform Enterprise] Creating EXT4 filesystem on disk at '$device'" | tee -a $log_pathname^M$
^M$
  mkfs.ext4 -m 0 -E lazy_itable_init=0,lazy_journal_init=0,discard $device^M$
fi^M$
^M$
echo "[Terraform Enterprise] Creating mounted disk directory at '${disk_path}'" | tee -a $log_pathname^M$
mkdir --parents ${disk_path}^M$
^M$
echo "[Terraform Enterprise] Mounting disk '$device' to directory at '${disk_path}'" | tee -a $log_pathname^M$
mount --options discard,defaults $device ${disk_path}^M$
chmod og+rw ${disk_path}^M$
^M$
echo "[Terraform Enterprise] Configuring automatic mounting of '$device' to directory at '${disk_path}' on reboot" | tee -a $log_pathname^M$
echo "UUID=$(lsblk --noheadings --output uuid $device) ${disk_path} ext4 discard,defaults 0 2" >> /etc/fstab^M$
^M$
%{ endif ~}^M$
echo "[Terraform Enterprise] Creating Terraform Enterprise library directory at '${lib_directory}'" | tee -a $log_pathname^M$
mkdir -p ${lib_directory}^M$
^M$
echo "[Terraform Enterprise] Writing data of license secret '${license_secret}' to '${lib_directory}'" | tee -a $log_pathname^M$
http_proxy="" https_proxy="" gcloud secrets versions access latest --secret="${license_secret}" | \^M$
  base64 --decode --ignore-garbage > ${license_file_location}^M$
^M$
%{ if ssl_certificate_secret != null ~}^M$
echo "[Terraform Enterprise] Writing data of SSL certificate secret '${ssl_certificate_secret}' to '${ssl_certificate_pathname}'" | tee -a $log_pathname^M$
http_proxy="" https_proxy="" gcloud secrets versions access latest --secret="${ssl_certificate_secret}" | \^M$
  base64 --decode --ignore-garbage > ${ssl_certificate_pathname}^M$
^M$
%{ endif ~}^M$
%{ if ssl_private_key_secret != null ~}^M$
echo "[Terraform Enterprise] Writing data of SSL private key secret '${ssl_private_key_secret}' to '${ssl_private_key_pathname}'" | tee -a $log_pathname^M$
http_proxy="" https_proxy="" gcloud secrets versions access latest --secret="${ssl_private_key_secret}" | \^M$
  base64 --decode --ignore-garbage > ${ssl_private_key_pathname}^M$
^M$
%{ endif ~}^M$
%{ if airgap_url != null ~}^M$
echo "[Terraform Enterprise] Copying airgap storage object '${airgap_url}' to '${airgap_pathname}'" | tee -a $log_pathname^M$
http_proxy="" https_proxy="" gsutil cp ${airgap_url} ${airgap_pathname}^M$
^M$
%{ endif ~}^M$
%{ if monitoring_enabled ~}^M$
monitoring_agent_url="https://dl.google.com/cloudagents/add-monitoring-agent-repo.sh"^M$
monitoring_agent_pathname="/tmp/add-monitoring-agent-repo.sh"^M$
echo "[Terraform Enterprise] Downloading Cloud Monitoring agent script from '$monitoring_agent_url' to '$monitoring_agent_pathname'" | tee -a $log_pathname^M$
curl -sS -o $monitoring_agent_pathname $monitoring_agent_url^M$
^M$
echo "[Terraform Enterprise] Executing Cloud Monitoring agent script at '$monitoring_agent_pathname'" | tee -a $log_pathname^M$
chmod +x $monitoring_agent_pathname^M$
bash $monitoring_agent_pathname^M$
^M$
echo "[Terraform Enterprise] Installing Cloud Monitoring agent" | tee -a $log_pathname^M$
if [[ $distribution == "ubuntu" ]]^M$
then^M$
  apt-get --assume-yes update^M$
  apt-get --assume-pes install stackdriver-agent^M$
elif [[ $distribution == "rhel" ]]^M$
then^M$
  yum install --assumeyes stackdriver-agent^M$
fi^M$
^M$
echo "[Terraform Enterprise] Starting Cloud Monitoring agent service" | tee -a $log_pathname^M$
service stackdriver-agent start^M$
%{ endif ~}^M$
^M$
echo "[Terraform Enterprise] Reading private IP address of compute instance from Metadata service" | tee -a $log_pathname^M$
private_ip=$(curl -H "Metadata-Flavor: Google" "http://169.254.169.254/computeMetadata/v1/instance/network-interfaces/0/ip")^M$
^M$
install_url="https://get.replicated.com/docker/terraformenterprise/active-active"^M$
install_pathname="/tmp/install.sh"^M$
echo "[Terraform Enterprise] Downloading Terraform Enterprise installation script from '$install_url' to '$install_pathname'" | tee -a $log_pathname^M$
curl -o $install_pathname $install_url^M$
^M$
echo "[Terraform Enterprise] Executing Terraform Enterprise installation script at '$install_pathname'" | tee -a $log_pathname^M$
chmod +x $install_pathname^M$
$install_pathname \^M$
  fast-timeouts \^M$
  private-address="$private_ip" \^M$
  public-address="$private_ip" \^M$
  %{ if proxy_ip != null ~}^M$
  http-proxy="${proxy_ip}" \^M$
  additional-no-proxy="${no_proxy}" \^M$
  %{ else ~}^M$
  no-proxy \^M$
  %{ endif ~}^M$
  %{if enable_active_active ~}^M$
  disable-replicated-ui \^M$
  %{ endif ~}^M$
  | tee -a $log_pathname^M$
^M$
%{ if custom_image_tag != null ~}^M$
%{ if length(regexall("^.+-docker\\.pkg\\.dev|^.*\\.?gcr\\.io", custom_image_tag)) > 0 ~}^M$
echo "[Terraform Enterprise] Registering gcloud as a Docker credential helper" | tee -a^M$
gcloud auth configure-docker --quiet ${split("/", custom_image_tag)[0]}^M$
^M$
%{ endif ~}^M$
echo "[Terraform Enterprise] Pulling custom worker image '${custom_image_tag}'" | tee -a^M$
docker pull ${custom_image_tag}^M$
%{ endif ~}^M$`

**Comment by serg060606** [comment]
@

**Comment by aaron-lane** [comment]
@serg060606 thank you. I believe that I understand the issue now. You are executing Terraform in a Windows environment, which is causing the the templated files to have Windows line endings rather than Unix line endings, resulting in an error when the startup script is executed in Ubuntu or RHEL.

I have opened #132 which I think will solve this issue for you. Please test the `aaron-lane-replace-windows-line-endings` branch to see if this issue is solved for you.

**Comment by serg060606** [comment]
@aaron-lane 
you are totally right, repo clone in linux fixed the windows format issue. otherwise it's adding everywhere "^M"
thank you

**Comment by aaron-lane** [comment]
@serg060606 are you able to test #132?

**Comment by serg060606** [comment]
@aaron-lane even without it works ok, just have to make pull from linux pc.
thank you.
