### ISSUE TITLE
Encryption password must be set or install fails on RHEL

### ISSUE THREAD

**Issue by amy-hashi** [hashicorp/terraform-google-terraform-enterprise#28]
## Issue

The default value for `encryption_password` is set to null. If no value is passed, the install will error with ```startup-script: INFO startup-script: cat: /etc/ptfe/encpasswd: No such file or directory
startup-script: INFO startup-script: Return code 1.
startup-script: INFO Finished running startup scripts.```

## Workaround

Pass a value for `encryption_password` to avoid this issue on RHEL. 

## Effects

RHEL on GCP with no value set for `encryption_password`. 

This issue does not exist on Ubuntu.

**Comment by mocofound** [comment]
I was able to reproduce this issue in my lab on RHEL image_family="rhel-7-v20190729".  My test is in addition to a second party previously reporting the issue.

Unfortunately, I have been unable to successfully use the workaround listed above (set value for encryption_password).

Even with encryption_password specified in my .tfvars file, I am still getting the same error 
`tfe-primary-0-zfsx startup-script: INFO startup-script: cat: /etc/ptfe/encpasswd: No such file or directory`

Currently, there is no encpasswd file in the /etc/ptfe directory.

**Comment by amy-hashi** [comment]
Resolved in v0.1.1. If an encryption password is not set, one will be generated for you.
