### ISSUE TITLE
Unable to use module when CloudDNS not in the same project

### ISSUE THREAD

**Issue by mengesb** [hashicorp/terraform-google-terraform-enterprise#6]
https://github.com/hashicorp/terraform-google-terraform-enterprise/blob/26f04578edc0bddfcb8614dbb55fb77e644312b6/primary.tf#L53

This won't work if the DNS zone is not part of the credentials default project. Generally this will always be the case in something like a SharedVPC model.

**Comment by amy-hashi** [comment]
Thanks for the feedback. We should be able to add the option to specify a project for this bit fairly easily.

**Comment by amy-hashi** [comment]
Fix has been merged, and will go into the next release. You can test this by pointing your module at the github repo instead of the registry if you want to test.

**Comment by amy-hashi** [comment]
v0.0.3-beta has been released that contains the fix for this. Closing this out.
